# Generated by Django 5.2.3 on 2025-06-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='fname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='lname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='', max_length=15),
        ),
    ]
