# Generated by Django 5.2.3 on 2025-06-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='address',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(default=''),
        ),
    ]
