# Generated by Django 5.2.3 on 2025-06-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_enquiry_address_enquiry_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField()),
                ('fname', models.CharField()),
                ('gender', models.CharField()),
                ('dobirth', models.DateField()),
                ('address', models.CharField()),
                ('mobile', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField()),
                ('department', models.CharField()),
                ('dojoin', models.DateField()),
                ('pimage', models.BinaryField()),
            ],
        ),
    ]
