# Generated by Django 5.2.3 on 2025-06-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_facultyregister_pimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyregister',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='facultyregister',
            name='department',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='facultyregister',
            name='fname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='facultyregister',
            name='fullname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='facultyregister',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='facultyregister',
            name='qualification',
            field=models.CharField(max_length=30),
        ),
    ]
