# Generated by Django 5.2.3 on 2025-06-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_facultyregister_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('depaertment', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='FacultyRegister',
        ),
    ]
