# Generated by Django 5.2.3 on 2025-06-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_faculty_delete_facultyregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dobirth',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dojoin',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='faculty',
            name='gender',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='faculty',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='faculty',
            name='pimage',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='faculty',
            name='qualification',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='depaertment',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='fullname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
