# Generated by Django 5.2.3 on 2025-06-26 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_faculty_address_faculty_dobirth_faculty_dojoin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='pimage',
        ),
    ]
