# Generated by Django 5.2.3 on 2025-06-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_faculty_pimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='fname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
