# Generated by Django 5.2.3 on 2025-06-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_faculty_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='dobirth',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='dojoin',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
    ]
