# Generated by Django 5.2.3 on 2025-06-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_depaertment_faculty_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='fname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='dobirth',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='dojoin',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
