# Generated by Django 5.2.3 on 2025-06-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_facultyregister_delete_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyregister',
            name='pimage',
            field=models.ImageField(blank=True, upload_to='pimage'),
        ),
    ]
