# Generated by Django 5.2.3 on 2025-06-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_facultyregister_pimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyregister',
            name='pimage',
        ),
    ]
