# Generated by Django 5.2.3 on 2025-06-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_facultyregister_pimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('father', models.CharField()),
                ('gender', models.CharField()),
                ('dob', models.DateField()),
                ('address', models.CharField()),
                ('mobile', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField()),
                ('image', models.ImageField(blank=True, upload_to='image')),
                ('sign', models.ImageField(blank=True, upload_to='sign')),
            ],
        ),
    ]
