# Generated by Django 5.2.3 on 2025-07-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_feesdeposite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feesdeposite',
            old_name='date_paid',
            new_name='datePaid',
        ),
        migrations.RenameField(
            model_name='feesdeposite',
            old_name='student',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='feesdeposite',
            old_name='payment_method',
            new_name='paymentMode',
        ),
        migrations.RemoveField(
            model_name='feesdeposite',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='feesdeposite',
            name='selectYear',
        ),
        migrations.AddField(
            model_name='feesdeposite',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
        ),
        migrations.AddField(
            model_name='feesdeposite',
            name='batch',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='feesdeposite',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
        ),
        migrations.AddField(
            model_name='feesdeposite',
            name='paidAmount',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
        ),
        migrations.AddField(
            model_name='feesdeposite',
            name='totalFees',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feesdeposite',
            name='department',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='feesdeposite',
            name='semester',
            field=models.CharField(default='', max_length=2),
        ),
    ]
