# Generated by Django 5.2.3 on 2025-07-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_date_paid_feesdeposite_datepaid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesdeposite',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feesdeposite',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feesdeposite',
            name='paidAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feesdeposite',
            name='totalFees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
