# Generated by Django 5.2.3 on 2025-07-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_feesdeposite_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feesdeposite',
            name='name',
        ),
        migrations.AddField(
            model_name='feesdeposite',
            name='buildingfee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feesdeposite',
            name='decidedamt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feesdeposite',
            name='hostelfee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feesdeposite',
            name='otherfee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feesdeposite',
            name='tuitionfee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feesdeposite',
            name='year',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='feesdeposite',
            name='paymentMode',
            field=models.CharField(max_length=50),
        ),
    ]
