# Generated by Django 5.2.3 on 2025-07-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_feesdeposite_name_feesdeposite_buildingfee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesdeposite',
            name='semester',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='feesdeposite',
            name='year',
            field=models.CharField(default=''),
        ),
    ]
