# Generated by Django 5.2.3 on 2025-07-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_faculty_delete_facultyregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField()),
                ('year', models.CharField()),
                ('syllabus', models.FileField(upload_to='syllabus')),
            ],
        ),
    ]
