# Generated by Django 5.2.3 on 2025-07-08 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecideFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(default='')),
                ('department', models.CharField(default='')),
                ('decidedamt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hostelfee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tuitionfee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transportationfee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('otherfee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='home.student')),
            ],
        ),
        migrations.DeleteModel(
            name='FeesDeposite',
        ),
    ]
