# Generated by Django 5.2.3 on 2025-07-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_rename_name_decidefees_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decidefees',
            old_name='tuitionfee',
            new_name='examfee',
        ),
        migrations.AddField(
            model_name='decidefees',
            name='totalfee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
