# Generated by Django 5.2.3 on 2025-07-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_rename_tuitionfee_decidefees_examfee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decidefees',
            old_name='department',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='decidefees',
            old_name='batch',
            new_name='session',
        ),
        migrations.RemoveField(
            model_name='decidefees',
            name='examfee',
        ),
        migrations.RemoveField(
            model_name='decidefees',
            name='hostelfee',
        ),
        migrations.RemoveField(
            model_name='decidefees',
            name='otherfee',
        ),
        migrations.RemoveField(
            model_name='decidefees',
            name='totalfee',
        ),
        migrations.RemoveField(
            model_name='decidefees',
            name='transportationfee',
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
