# Generated by Django 5.2.3 on 2025-07-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_rename_department_decidefees_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.CharField(default='', max_length=20),
        ),
    ]
