# Generated by Django 5.2.3 on 2025-07-10 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decidefees',
            name='s_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='decidefees',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fees', to='home.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.CharField(default=''),
        ),
    ]
