# Generated by Django 5.2.3 on 2025-07-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_remove_decidefees_s_id_remove_student_student_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decidefees',
            old_name='student',
            new_name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.CharField(default='', max_length=20),
        ),
    ]
