# Generated by Django 5.2.3 on 2025-07-10 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_rename_student_decidefees_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decidefees',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decide_fees', to='home.student', to_field='student_id'),
        ),
        migrations.CreateModel(
            name='DecideExamF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default='', max_length=50)),
                ('course', models.CharField(default='', max_length=100)),
                ('decidedexam', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decide_examsf', to='home.student', to_field='student_id')),
            ],
        ),
        migrations.CreateModel(
            name='DecideHostelF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default='', max_length=50)),
                ('course', models.CharField(default='', max_length=100)),
                ('decidedexam', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decide_hostelf', to='home.student', to_field='student_id')),
            ],
        ),
        migrations.CreateModel(
            name='DecideTransportationF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default='', max_length=50)),
                ('course', models.CharField(default='', max_length=100)),
                ('decidedexam', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decide_transportationf', to='home.student', to_field='student_id')),
            ],
        ),
    ]
