# Generated by Django 5.2.3 on 2025-07-11 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_decidefees_student_id_decideexamf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decidehostelf',
            old_name='decidedexam',
            new_name='decidedeHfee',
        ),
        migrations.RenameField(
            model_name='decidetransportationf',
            old_name='decidedexam',
            new_name='decidedTfee',
        ),
    ]
