# Generated by Django 5.2.3 on 2025-07-11 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_rename_decidedexam_decidehostelf_decidedehfee_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DecideExamF',
            new_name='DecideExamFee',
        ),
        migrations.RenameModel(
            old_name='DecideHostelF',
            new_name='DecideHostelFee',
        ),
        migrations.RenameModel(
            old_name='DecideTransportationF',
            new_name='DecideTransportationFee',
        ),
    ]
