# Generated by Django 5.2.3 on 2025-07-11 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_rename_decideexamf_decideexamfee_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DecideTransportationFee',
        ),
    ]
