# Generated by Django 5.2.3 on 2025-07-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_delete_decidetransportationfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decidehostelfee',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='DecideExamFee',
        ),
        migrations.DeleteModel(
            name='DecideHostelFee',
        ),
    ]
