# Generated by Django 5.2.3 on 2025-07-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_student_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decidefees',
            old_name='student_id',
            new_name='student',
        ),
    ]
