# Generated by Django 5.2.3 on 2025-07-11 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_rename_student_id_decidefees_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecideExamFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default='', max_length=50)),
                ('course', models.CharField(default='', max_length=100)),
                ('decidedexamfee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decide_exam_fees', to='home.student', to_field='student_id')),
            ],
        ),
    ]
