# Generated by Django 5.2.3 on 2025-07-11 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_decideexamfees'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecideHostelFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default='', max_length=50)),
                ('course', models.CharField(default='', max_length=100)),
                ('decidedhostelfee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decide_hostel_fees', to='home.student', to_field='student_id')),
            ],
        ),
        migrations.CreateModel(
            name='DecideTransportFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default='', max_length=50)),
                ('course', models.CharField(default='', max_length=100)),
                ('decidedtransportfee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decide_transport_fees', to='home.student', to_field='student_id')),
            ],
        ),
    ]
