# Generated by Django 5.2.3 on 2025-07-12 04:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_decidehostelfees_decidetransportfees'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('cheque', 'Cheque')], max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('decide_fees', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('dpfees', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('pending', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('dpdate', models.DateField(default=django.utils.timezone.now)),
                ('receipt', models.CharField(editable=False, max_length=20, unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dp_academics_fees', to='home.student', to_field='student_id')),
            ],
        ),
    ]
