# Generated by Django 5.2.3 on 2025-07-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_dpfees'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpfees',
            name='remark',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
