# Generated by Django 5.2.3 on 2025-07-12 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_dpfees_remark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DpFees',
        ),
    ]
