# Generated by Django 5.2.3 on 2025-07-12 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_dpfees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpfees',
            name='decide_fees',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dpfees',
            name='dpfees',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dpfees',
            name='payment_mode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dpfees',
            name='pending',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dpfees',
            name='receipt',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='dpfees',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dpfees',
            name='session',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dpfees',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposite_academic_fees', to='home.student', to_field='student_id'),
        ),
    ]
