# Generated by Django 5.2.3 on 2025-07-14 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_alter_dpfees_decide_fees_alter_dpfees_dpfees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpfees',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposite_academics_fees', to='home.student', to_field='student_id'),
        ),
        migrations.CreateModel(
            name='DpExamFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('decide_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dpexamfees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pending', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.TextField(blank=True, null=True)),
                ('payment_mode', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposite_exam_fees', to='home.student', to_field='student_id')),
            ],
        ),
    ]
