# Generated by Django 5.2.3 on 2025-07-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_alter_dpfees_student_dpexamfees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpexamfees',
            name='receipt',
            field=models.CharField(max_length=30),
        ),
    ]
