# Generated by Django 5.2.3 on 2025-07-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_dptransportfees'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('mobile', models.CharField(default='')),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField()),
            ],
        ),
    ]
