# Generated by Django 5.2.3 on 2025-07-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_quickenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('father', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('dateofbirth', models.DateField()),
                ('adhar', models.CharField(max_length=12, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='staff_profiles/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='staff_resumes/')),
                ('department', models.CharField(max_length=100)),
                ('date_of_join', models.DateField()),
                ('skills', models.JSONField(default=list)),
                ('maxQualification', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
