# Generated by Django 5.2.3 on 2025-07-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dobirth', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('qualification', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('dojoin', models.DateField()),
                ('password', models.CharField(max_length=128)),
                ('profile', models.ImageField(blank=True, upload_to='FacultyProfile')),
                ('resume', models.FileField(blank=True, upload_to='FacultyResume')),
            ],
        ),
    ]
