# Generated by Django 5.2.3 on 2025-07-21 09:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_facultymember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymember',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='FacultyProfile'),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='FacultyResume'),
        ),
        migrations.CreateModel(
            name='FacultyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=uuid.uuid4, max_length=40, unique=True)),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.facultymember')),
            ],
        ),
    ]
