# Generated by Django 5.2.3 on 2025-10-30 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_alter_attendancerecord_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'date')},
        ),
    ]
