# Generated by Django 5.2.3 on 2025-10-31 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_alter_attendancerecord_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-date', 'time_in']},
        ),
    ]
